// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Track is the predicate function for track builders.
type Track func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
