// Code generated by entc, DO NOT EDIT.

package track

const (
	// Label holds the string label denoting the track type in the database.
	Label = "track"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date vertex property in the database.
	FieldDate = "date"

	// Table holds the table name of the track in the database.
	Table = "tracks"
)

// Columns holds all SQL columns for track fields.
var Columns = []string{
	FieldID,
	FieldDate,
}
